version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: "time-tracker-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=database
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017